token_cleaning
yral-dapp/yral-backend-cloudflare-workers pull request #5
Opened 2024-12-30 05:08 UTC by harsh-mahajan-yral

- snapshot and KV setup

2025-01-07 06:29 UTC, harsh-mahajan-yral commented
https://github.com/yral-dapp/hot-or-not-web-leptos-ssr/issues/540

2025-01-08 05:28 UTC, harshita-srivastava-yral commented
Not able to see preview link for testing this out. Can you please check? @harsh-mahajan-yral

2025-01-08 05:49 UTC, ravi-sawlani-yral requested changes

2025-01-08 05:49 UTC, ravi-sawlani-yral commented on workers/icpump_token_cleanup/src/lib.rs
> +//     }
Is the commented code required?

2025-01-08 05:49 UTC, ravi-sawlani-yral commented on workers/icpump_token_cleanup/src/lib.rs
> +}
How is this validation logic correct? `icpump.fun` is not a correct metric to decide if the token is valid.

2025-01-08 05:52 UTC, ravi-sawlani-yral commented
The way to validate token is to check if it is present in canisters. I don't see any code that validates tokens from canisters.

2025-01-09 05:41 UTC, harshita-srivastava-yral commented
Updated PR to be attached today

2025-01-13 05:47 UTC, ravi-sawlani-yral requested changes

2025-01-13 05:47 UTC, ravi-sawlani-yral commented on workers/icpump_token_cleanup/src/lib.rs
> +    ).map_err(|e| Error::from(e.to_string()))?;
We don't need an identity. All of the calls that would be required is public. You can skip the identity.

2025-01-13 05:47 UTC, ravi-sawlani-yral commented on workers/icpump_token_cleanup/src/lib.rs
> +        .map_err(|e| Error::from(e.to_string()))?;
This is just one user index there are about 15 user indexes, the individual canister can be under any of them. Instead use the public endpoint `https://yral-metadata.dev/metadata/<user-principal>` to retrieve the user-canister id.

2025-01-13 05:47 UTC, ravi-sawlani-yral commented on workers/icpump_token_cleanup/src/lib.rs
> +    }
This is not valid check. This is checking if user canister is present. User canister can be present but the token canister might be deleted. We need to check if the token canister is present or not. use `deployed_cdao_canisters` in individual canister can then verify if the root canister is present in it.

2025-01-13 05:49 UTC, ravi-sawlani-yral commented
Please attach the issue that you are trying to fix with this PR.

2025-01-14 10:55 UTC, ravi-sawlani-yral commented on workers/icpump_token_cleanup/src/lib.rs
> +        .map_err(|e| Error::from(e.to_string()))?;
You could also generate rust agent bindings for individual canister using `didc` tool. That way it would be easier and less chances of mistake.

2025-01-15 06:24 UTC, ravi-sawlani-yral requested changes

2025-01-15 06:24 UTC, ravi-sawlani-yral commented on workers/icpump_token_cleanup/src/lib.rs
> +        .with_url("https://a4gq6-oaaaa-aaaab-qaa4q-cai.raw.ic0.app")
```suggestion
        .with_url("https://ic0.app")
```

2025-01-15 06:25 UTC, ravi-sawlani-yral commented
There is one minor change rest all looks good. But first try to test it on test data.

2025-01-15 06:47 UTC, harsh-mahajan-yral commented
will try to test it today

2025-01-17 05:39 UTC, tushar-saxena-yral commented on workers/icpump_token_cleanup/wrangler.toml
> +name = "icpump_token_cleanup"
you are missing the shim:
https://github.com/yral-dapp/yral-backend-cloudflare-workers/blob/c345ffa7b6912330a32d610db58ae93a6f83a333/workers/storj-bulk-upload/wrangler.toml#L2

2025-01-20 06:27 UTC, ravi-sawlani-yral approved these changes

2025-01-20 16:50 UTC, merged